#page title
page_title                                : $DUCKIE The MEME Token                    # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://dexscreener.com/blast/0xfe5bfd86774df006eda3627e3eba361cfc64e82a # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo.png                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : $DUCKIE The MEME Token                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Have you seen a duck reaching the moon?   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Welcome to $DUCKIE, the first MEME project to be launched on TokenFi and Blast L2.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : The Duckie Family                                
your_link                                 :                      
your_city                                 : The World of Ducks. All Rights Reserved.                                
email_address                             : onefridge@duckie.social
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : duckiethetoken
telegram_username                         : duckiethetoken
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Awesome Airdrop
    description                           : By rewarding TokenFi & Floki holders, our airdrop helps to onboard the best crypto holders and diamond hands.
    fontawesome_icon_name                 : gem
    
  - title                                 : Built For The Community
    description                           : All the tokens not sale on the public round are burned. Plus, we have simple tokenomics with no tax, no fee whatsoever.
    fontawesome_icon_name                 : users

  - title                                 : Simply The Best
    description                           : Being the first MEME project on TokenFi and Blast L2, $DUCKIE is simply the best.
    fontawesome_icon_name                 : star

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
